name: Provision Konnect Team resources

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        type: choice
        options:
          - provision
          - destroy
        default: 'provision'

env:
  KONNECT_RESOURCES_FILE: ${{ github.workspace }}/konnect/resources.yaml
  VAULT_ADDR: ${{ vars.VAULT_ADDR }}
  AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
  SYSTEM_ACCOUNT_TOKEN: ${{ vars.SYSTEM_ACCOUNT_TOKEN }}

jobs:
  provision-konnect:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC token generation
      contents: read    # Required to checkout code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get secrets from Vault
        uses: hashicorp/vault-action@v3
        id: import-secrets
        with:
          url: ${{ vars.VAULT_ADDR }}
          method: jwt
          path: github-actions           
          role: ${{ vars.KONNECT_TEAM_NAME }}-gh-repo-role
          exportToken: true  # exports the env.VAULT_TOKEN
          secrets: |
            ${{ vars.KONNECT_TEAM_NAME }}-kv/data/system-accounts/sa-${{ vars.KONNECT_TEAM_NAME }} token | SYSTEM_ACCOUNT_TOKEN ;
      
      # - name: Import system account Token from Vault
      #   id: import-token
      #   uses: hashicorp/vault-action@v2
      #   with:
      #     url: ${{ vars.VAULT_ADDR }}
      #     token: ${{ secrets.VAULT_TOKEN }}
      #     secrets: |
      #       ${{ vars.KONNECT_TEAM_NAME }}-kv/data/system-accounts/sa-${{ vars.KONNECT_TEAM_NAME }} token | SYSTEM_ACCOUNT_TOKEN ;

      - name: Provision Konnect Resources
        uses: dennyh89-demo/kw-platform-ops/.github/actions/provision-konnect-resources@main
        with:
          action: ${{ inputs.action }}
          konnect-resources: ${{ env.KONNECT_RESOURCES_FILE }}
          vault-address: ${{ env.VAULT_ADDR }}
          vault-token: ${{ env.VAULT_TOKEN }} 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          konnect-token: ${{ steps.import-secrets.outputs.SYSTEM_ACCOUNT_TOKEN }}
          konnect-team-name: ${{ vars.KONNECT_TEAM_NAME }}
          s3-prefix: ${{vars.S3_PREFIX}}
